const express = require("express")
const app = express()
const bienvenueRoute = require("./routes/bienvenue")
const userRoute = require("./routes/user")
const bodyParser = require("body-parser")
const groupeRoute = require("./routes/groupes")
const deviseRoute = require("./routes/devise")
const userGroupeRoute = require("./routes/userGroupes")
const menuRoute = require("./routes/menus")
const ongletRoute = require("./routes/onglets")
const modeAccesRoute = require("./routes/modeacces")
const privilegeRoute = require("./routes/privileges")
const paysRoute = require("./routes/pays")
const prestaireRoute = require("./routes/prestataire")
const structureRoute = require("./routes/structure")
const regionsRoute = require("./routes/regions")
const prefectureRoutes = require("./routes/prefectures")
const quartiersRoutes = require("./routes/quartier")
const communesRoutes = require("./routes/communes")
const axeRoutes = require("./routes/axe")
const chaineRoutes = require("./routes/chaineResultat")
const programmeRoutes = require("./routes/programme")
const prioriteRoutes = require("./routes/priorite")
const projetRoutes = require("./routes/projet")
const financementRoutes = require("./routes/financement")
const actionRoutes = require("./routes/actions")
const statuProjetRoutes = require("./routes/statutprojet")
const serviceConcerneRoutes = require("./routes/serviceconcerne")
const serviceRoutes = require("./routes/service")
const checktokenexpire = require("./routes/checktokenexpire")
const categorieactionRoute = require("./routes/categorieaction")
const categorieinvestRoute = require("./routes/categorieinves")
const typeDocumentRoute = require("./routes/typeDocument")
const typeExpertiseRoute = require("./routes/typeExpertise")
const rubriqueEvaluationRoute = require("./routes/rubriqueEvaluation")
const applicationRoute = require("./routes/application")
const couleurRoute = require("./routes/couleur");
const uniteRoute = require("./routes/unite")
const anneecibleRoute = require("./routes/anneecible")
const budgetPrevisionnelRoute = require("./routes/budgetprevisionnel")
const interventionRoute = require("./routes/intervention")
const documentRoute = require("./routes/document")
const executionRoute = require("./routes/execution")
const indicateurRoutes = require("./routes/indicateur")
const investissementRoute = require("./routes/investissement")
const hypotheseRoute = require("./routes/hypothese")
const rubriqueRoute = require("./routes/rubrique")
const evaluationRoute = require("./routes/evaluation")
const valeurCibleRoute = require("./routes/valeurcible")
const chapitreRoute = require("./routes/chapitre")
const sousProgrammeRoute = require("./routes/sousprogramme")
const papbRoute = require("./routes/papb")
const paabRoute = require("./routes/paab")
const programmegrleRoute = require("./routes/programmegrle")
const defiPgPrioRoute = require("./routes/defisprgpriroritaire")
const pgprioritaireRoute = require("./routes/programmeprioritaire")
const resultatRoute = require("./routes/resultat")
const activiteRoute = require("./routes/activite")
const strategieRoute = require("./routes/strategie")
const tacheRoute = require("./routes/tache")
const activitePaabRoute = require("./routes/activitepaab")
const activiteServiceRoute = require("./routes/activiteservice")
const cdmtProgrammeRoute = require("./routes/cdmtprogrammes")
const cdmtNatDepenseRoute = require("./routes/cdmtnatdepenses")
const activiteprojetRoute = require("./routes/activiteprojet")
const departementRoute = require("./routes/departement")
const natureRoute = require("./routes/nature")
const activitetacheRoute = require("./routes/activitetache")
const qteprevisionnelleRoute = require("./routes/qteprevisionnelle")
const templateRoute = require("./routes/template")

app.use(bodyParser.json())

app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Headers', 'Authorization, X-API-KEY, Origin, X-Requested-With, Content-Type, Accept');
    res.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, DELETE');

    next();
});

app.use("/api", checktokenexpire)
app.use("/api", bienvenueRoute)
app.use("/api", userRoute)
app.use("/api", groupeRoute)
app.use("/api", userGroupeRoute)
app.use("/api", menuRoute),
app.use("/api", ongletRoute)
app.use("/api", modeAccesRoute)
app.use("/api", privilegeRoute)
app.use("/api", paysRoute)
app.use("/api", couleurRoute)
app.use("/api", prestaireRoute)
app.use("/api", structureRoute)
app.use("/api", regionsRoute)
app.use("/api", prefectureRoutes)
app.use("/api", quartiersRoutes)
app.use("/api", communesRoutes)
app.use("/api", axeRoutes)
app.use("/api", deviseRoute)
app.use("/api", programmeRoutes)
app.use("/api", prioriteRoutes)
app.use("/api", financementRoutes)
app.use("/api", projetRoutes)
app.use("/api", actionRoutes)
app.use("/api", statuProjetRoutes)
app.use("/api", serviceConcerneRoutes)
app.use("/api", serviceRoutes)
app.use("/api", categorieactionRoute)
app.use("/api", categorieinvestRoute)
app.use("/api", uniteRoute)
app.use("/api", anneecibleRoute)
app.use("/api", typeDocumentRoute)
app.use("/api", typeExpertiseRoute)
app.use("/api", rubriqueEvaluationRoute)
app.use("/api", applicationRoute)
app.use("/api", budgetPrevisionnelRoute)
app.use("/api", documentRoute)
app.use("/api", interventionRoute)
app.use("/api", executionRoute)
app.use("/api", investissementRoute)
app.use("/api", chaineRoutes)
app.use("/api", indicateurRoutes)
app.use("/api", hypotheseRoute)
app.use("/api", rubriqueRoute)
app.use("/api", evaluationRoute)
app.use("/api", chapitreRoute)
app.use("/api", programmegrleRoute)
app.use("/api", pgprioritaireRoute)
app.use("/api", papbRoute)
app.use("/api", paabRoute)
app.use("/api", resultatRoute)
app.use("/api", defiPgPrioRoute)
app.use("/api", sousProgrammeRoute)
app.use("/api", activiteRoute)
app.use("/api", tacheRoute)
app.use("/api", strategieRoute)
app.use("/api", activitePaabRoute)
app.use("/api", cdmtProgrammeRoute)
app.use("/api", cdmtNatDepenseRoute)
app.use("/api", activiteServiceRoute)
app.use("/api", activiteprojetRoute)
app.use("/api", departementRoute)
app.use("/api", natureRoute)
app.use("/api", activitetacheRoute)
app.use("/api", templateRoute)
app.use("/api", qteprevisionnelleRoute)

module.exports = app
